= Nula - Programing Language

= installation
== Normal installation
=== For Windows
[source,bash]
----
curl -L -o /tmp/install.ps1 https://raw.githubusercontent.com/Nula-Lang/Nula/main/install/install.ps1
----
==== For Linux/Unix/Macos
[source,bash]
----
curl -L -o /tmp/install.sh https://raw.githubusercontent.com/Nula-Lang/Nula/main/install/install.sh
----
== Building from source
=== For Windows
[source,bash]
----
curl -L -o /tmp/build-from-source.sh https://raw.githubusercontent.com/Nula-Lang/Nula/main/install/build-from-source.ps1
----
=== For Linux/Unix/Macos
[source,bash]
----
curl -L -o /tmp/build-from-source.sh https://raw.githubusercontent.com/Nula-Lang/Nula/main/install/build-from-source.sh
----
= About Nula
Nula was created in 28.09.2025

= Nula Language Documentation
:toc:
:toclevels: 2
:icons: font
:source-highlighter: rouge

== Wprowadzenie
**Nula** to nowoczesny, bardzo łatwy w użyciu język programowania.  
Cechuje się prostym i czytelnym syntaxem, wydajnością bliską C dzięki Zig oraz możliwością uruchamiania kodu w trybie interpretowanym dzięki Python.

Język pozwala również na tłumaczenie kodu z innych języków (np. Python) do Nula w prosty sposób.

=== Kluczowe cechy
* Syntax: `write` zamiast `print`
* Komentarze: `@` 
* Tłumaczenie kodu: `# = python = {print("hi")}`
* Zależności: `<(zaleznosc)>` lub `bottles.nula`
* Komendy CLI: `help`, `build`, `run`, `create`, `install {dep}`
* Wydajność: blisko C dzięki Zig

= Writing programs in nula
