[crypha-cybersecurity]
type = "git"
url = "https://github.com/Nula-Lang/crypha-lib.git"

[luma]
type = "bin"
url = "https://github.com/Nula-Lang/luma-lib/releases/download/v0.1/luma-lib"

[obsidian-gui]
type = "tar"
url = ""

[]
type = "zip"
url = ""

[]
type "http"
url = ""
