# Cargo.toml - Updated

[package]
name = "nula-compiler"
version = "1.0.0"
edition = "2021"

[dependencies]
cranelift = "0.110.0"
cranelift-module = "0.110.0"
cranelift-object = "0.110.0"
cranelift-codegen = "0.110.0"
cranelift-frontend = "0.110.0"
target-lexicon = "0.12.14"
